/**
 * Centralized constants for the GapSight compliance scoring engine.
 *
 * All thresholds, weights, and limits used in compliance checks.
 * No magic numbers should exist outside this file.
 *
 * @module constants
 */

// Human Oversight Scoring
const OVERSIGHT_WEIGHTS = [1, 3, 2, 2, 1];
const OVERSIGHT_PASS_THRESHOLD = 0.80;
const OVERSIGHT_REVIEW_THRESHOLD = 0.60;

// Context Flag Thresholds
const SMALL_TEST_SET_THRESHOLD = 30;
const STALE_MODEL_24M_MONTHS = 24;
const STALE_MODEL_12M_MONTHS = 12;

// Cross-Metric Rule Thresholds
const CROSS_ACCURACY_THRESHOLD = 0.90;
const CROSS_FAIRNESS_GAP_THRESHOLD = 0.15;
const CROSS_ROBUSTNESS_THRESHOLD = 0.80;
const CROSS_DRIFT_THRESHOLD = 0.20;
const CROSS_RETRAIN_MONTHS_THRESHOLD = 12;
const CROSS_FAIRNESS_MITIGATION_THRESHOLD = 0.10;
const CROSS_OVERSIGHT_THRESHOLD = 0.80;
const GPAI_SYSTEMIC_RISK_FLOPS = 1e25;

// Risk Level Thresholds
const RISK_FAIL_RATE_THRESHOLD = 0.30;
const RISK_REVIEW_RATE_THRESHOLD = 0.20;
const RISK_CROSS_CRITICAL_THRESHOLD = 2;

// Valid profile enum values
const VALID_ROLES = ['provider', 'deployer'];
const VALID_RISK_CATEGORIES = ['high-risk', 'limited', 'gpai'];
const VALID_DEPLOYMENT_STATUSES = ['pre-deployment', 'post-deployment', 'pilot'];

// Framework display names
const FRAMEWORK_NAMES = {
  eu_ai_act: 'EU AI Act',
  nist_ai_rmf: 'NIST RMF',
  iso_42001: 'ISO 42001',
};

module.exports = {
  OVERSIGHT_WEIGHTS,
  OVERSIGHT_PASS_THRESHOLD,
  OVERSIGHT_REVIEW_THRESHOLD,
  SMALL_TEST_SET_THRESHOLD,
  STALE_MODEL_24M_MONTHS,
  STALE_MODEL_12M_MONTHS,
  CROSS_ACCURACY_THRESHOLD,
  CROSS_FAIRNESS_GAP_THRESHOLD,
  CROSS_ROBUSTNESS_THRESHOLD,
  CROSS_DRIFT_THRESHOLD,
  CROSS_RETRAIN_MONTHS_THRESHOLD,
  CROSS_FAIRNESS_MITIGATION_THRESHOLD,
  CROSS_OVERSIGHT_THRESHOLD,
  GPAI_SYSTEMIC_RISK_FLOPS,
  RISK_FAIL_RATE_THRESHOLD,
  RISK_REVIEW_RATE_THRESHOLD,
  RISK_CROSS_CRITICAL_THRESHOLD,
  VALID_ROLES,
  VALID_RISK_CATEGORIES,
  VALID_DEPLOYMENT_STATUSES,
  FRAMEWORK_NAMES,
};
