export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-12">
      <h1 className="text-3xl font-bold">Terms of Service</h1>
      <p className="mt-2 text-sm text-gray-500">Last updated: March 2026</p>

      <section className="mt-8">
        <h2 className="text-xl font-semibold">Service Description</h2>
        <p className="mt-2 text-gray-700">
          GapSight is a free, open-source, informative self-assessment tool that helps AI teams identify
          potential compliance gaps relative to EU AI Act, NIST AI RMF, and ISO/IEC 42001. It is provided
          free of charge, as-is, without warranty of any kind, express or implied, including but not
          limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.
        </p>
      </section>

      <section className="mt-8">
        <h2 className="text-xl font-semibold">Not Legal Advice</h2>
        <p className="mt-2 text-gray-700">
          GapSight results are not legal advice and do not constitute a certificate of regulatory
          compliance. Results are indicative only and should be used as a starting point for compliance
          review. Users must consult qualified legal counsel for actual compliance obligations under the
          EU AI Act or any other regulation. GapSight is not a substitute for professional regulatory
          guidance.
        </p>
      </section>

      <section className="mt-8">
        <h2 className="text-xl font-semibold">Open Source License</h2>
        <p className="mt-2 text-gray-700">
          GapSight is open source software released under the MIT License. You are free to use, modify,
          and distribute it in accordance with the license terms. Assessment results generated by
          GapSight belong to you. The full license text is available at{' '}
          <a
            href="https://github.com/mmilovanovic87/gapsight/blob/main/LICENSE"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 hover:text-blue-800 underline"
          >
            github.com/mmilovanovic87/gapsight/blob/main/LICENSE
          </a>.
        </p>
      </section>

      <section className="mt-8">
        <h2 className="text-xl font-semibold">Availability</h2>
        <p className="mt-2 text-gray-700">
          GapSight is provided without a service level agreement (SLA) or uptime guarantee. The service
          may be modified, suspended, or discontinued at any time without notice. The knowledge base is
          updated periodically but is not guaranteed to reflect the most recent regulatory changes at
          any given time.
        </p>
      </section>

      <section className="mt-8">
        <h2 className="text-xl font-semibold">Prohibited Use</h2>
        <p className="mt-2 text-gray-700">
          You may not use GapSight to generate fraudulent compliance reports or to misrepresent your
          system's compliance status to regulators, auditors, or third parties. You are solely
          responsible for all decisions made based on GapSight output.
        </p>
      </section>

      <section className="mt-8">
        <h2 className="text-xl font-semibold">Limitation of Liability</h2>
        <p className="mt-2 text-gray-700">
          In no event shall the authors or contributors of GapSight be liable for any direct, indirect,
          incidental, special, or consequential damages arising from the use or inability to use this
          tool. Your use of GapSight is at your sole risk.
        </p>
      </section>

      <div className="mt-8 pt-6 border-t border-gray-200 text-sm text-gray-400">
        <p>ToS version: 1.0, March 2026</p>
      </div>
    </main>
  );
}
